### ISSUE TITLE
Style guide: provide links into framework documentation

### ISSUE THREAD

**Issue by ijdickinson** [vuejs/v2.vuejs.org#1174]
There are a couple of places in the style guide that I'm not quite sure what the recommendation means, and it would be really helpful to link back to the appropriate place in the main API documentation (when appropriate). 

For example, [keyed `v-for`](https://vuejs.org/v2/style-guide/index.html#Keyed-v-for-essential) is marked as essential, but I wasn't sure what the `:key` attrib actually did. However the [API entry for `key`](https://vuejs.org/v2/guide/list.html#key) was pretty clear.

So a general style-guide for the style-guide would be to link to the API or guide docs wherever possible!

**Comment by chrisvfritz** [comment]
Sounds great! I've already been trying to do this, but will make a dedicated pass to add more of these wherever I see a specific API referenced. 🙂

**Comment by ijdickinson** [comment]
Closing old ticket
