### ISSUE TITLE
Provide more information on how functional components evaluated

### ISSUE THREAD

**Issue by OEvgeny** [vuejs/v2.vuejs.org#1393]
Recently I stuck on the behavior mismatch between usual and functional components. According to the discussion [here](https://github.com/vuejs/vue/issues/7490) I propose to provide more information on how functional components work, which would make this aspect more understandable for end-users.

**Comment by chrisvfritz** [comment]
Thanks for opening this up. 🙂 We do already mention that functional components do not have their own instance distinct from their parent, which is the reason for the behavior you noticed. What kind of addition do you feel would have avoided the confusion?

**Comment by OEvgeny** [comment]
I think it could be done just more clearly.

I started to read from [Functional Components](https://vuejs.org/v2/guide/render-function.html#Functional-Components).
It says only:
> The anchored heading component we created earlier is relatively simple. It doesn’t manage any state, watch any state passed to it, and it has no lifecycle methods. Really, it’s only a function with some props.

And:

> Everything the component needs is passed through `context`, which is an object containing:
> - ...
> -  parent: A reference to the parent component

But nothing to indicate the difference between `component` and `functional-component` parent.

Next we are pointing out that:
> They’re also very useful as wrapper components. For example, when you need to:
> - Programmatically choose one of several other components to delegate to
> - Manipulate children, props, or data before passing them on to a child component

But nothing about the fact that such wrapping could break already established `provide/inject`.

I understand that `provide/inject` appeared after the guide was written. But can't see anything which could give me a clue why it stopped to work.

I think it would be better to describe how functional components evaluation is different from common components - some parts about the implementation which are under the hood. This imo should give the end-user some thoughts on when using a functional component in place of a component won't work.

If replacing/wrapping functional/common components doesn't provide any side effect, I wouldn't ask for such thing.

**Comment by OEvgeny** [comment]
> But nothing about the fact that such wrapping could break already established provide/inject.

I checked and seems it won't break. Sorry for a wrong assumption.

**Comment by OEvgeny** [comment]
@chrisvfritz Yes and no. This statement seems to me unresolved:
> But nothing to indicate the difference between component and functional-component parent.

Also the proposal seems almost suitable to me:
> I think it would be better to describe how functional components evaluation is different from common components - some parts about the implementation which are under the hood. This imo should give the end-user some thoughts on when using a functional component in place of a component won't work.

Just to be sure you have a right context, I'd add a quote of @LinusBorg from the related issue:
> This should indeed be documented more clearly, and not just in the context of provide/inject, but generally. Another side effect of this, for example, is that `context.parent` in the functional component it not `<provider>` - it's the main instance, in your example. Once again, the reason is that the functional component is being rendered in the parent's render cycle, not `<provider>`'s

**Comment by chrisvfritz** [comment]
I'd be open to a new section titled something like "Implications of Instanceless Components", right before the `Template Compilation` section. I wouldn't be able to write it myself any time soon, but a PR would be welcome. 🙂

**Comment by OEvgeny** [comment]
Closing as not actual
