### ISSUE TITLE
[cookbook] $route/query change handling

### ISSUE THREAD

**Issue by donnysim** [vuejs/v2.vuejs.org#1510]
I think it would be great to have a section for handling $route and/or query changes using vue-router as there are many forum and articles about it, but haven't found any [answers] that touch real case project problems.

For example:
`<router-view></router-view>` vs `<router-view :key="$route.fullPath"></router-view>` vs `<router-view :key="$route.path"></router-view>`. What they solve and what problems they introduce - e.g. performance, losing control over partial page updates etc..

I can think of couple example scenarios that could use some guidance:

- a query change does not mean that the page should reload all components, the user only switched the tab in a component (with query to be able to link to the tab), in addition it should not cause any components in page to reload their data;
- a `page` query param should reset to value `1` when a search filter is changed (can easily lead to infinite loops when watching `$route` and then resetting the `page` query param);
- there might be multiple components on the page that each depend on unique query params, but on change, only one should reload it's data, not both;
- advanced `back` button handling, e.g. an edit page with search uses `push` to add query changes to browser history, but the back button should go back to the previous page that brought the user to the edit page, not the last search query or the resources index page;

These are couple of example that would bring immense value if documented properly, yet each of them would require some layer around router and query handling. 

While I did propose this, I'm not confident in my abilities to solve this in a simple and understandable way 😅

**Comment by sdras** [comment]
This sounds great! I think it would be really helpful.

> While I did propose this, I'm not confident in my abilities to solve this in a simple and understandable way

If you can try your best to follow the format, I can help you shape the language and explanations. :) Teamwork!
