### ISSUE TITLE
[Cookbook] set up Vue storybook for rapid development/prototyping  

### ISSUE THREAD

**Issue by matteo-hertel** [vuejs/v2.vuejs.org#1516]
As per the title, a section of the cookbook could be used to explain how to set up a storybook with Vue for rapid prototyping / development.

A sensible structure could be:
- Why use a storybook
  - Brief description on why a storybook can be useful to build / prototype components 
- Basic example
  - Quickly set up a storybook
- Addons
  - For example https://www.npmjs.com/package/storybook-addon-vue-info

I'll be more than happy to contribute myself to this section of the cookbook 😄

**Comment by sdras** [comment]
Sounds great! I think this would be useful to people. Have you worked with storybook before? It has a few gotchas.

**Comment by matteo-hertel** [comment]
I have worked with storybook before yes and you're totally right there are a few gotchas, hopefully, nothing will be a showstopper for at least having the basic example so people can use it

**Comment by sdras** [comment]
Yeah, I don't think anything will get in your way too much, I just thought I'd mention in case you haven't worked with it before :) We can always add tips for how to handle things, that's where these recipes get very useful, IMO
