### ISSUE TITLE
[Cookbook] Deploy a Vue app to netifly/s3/firebase hosting CDN

### ISSUE THREAD

**Issue by matteo-hertel** [vuejs/v2.vuejs.org#1517]
As per the title, a section of the cookbook could be used to explain how to take an app from development to production and use a CDN to distribute the app

A good structure could be:
- How to configure a CDN
 - describe what needs to be configured/created for the given CDN
- How to manually deploy to a CDN
 - In my experience, it's much easier to manually deploy first and then configure some CI/CD pipeline
- CI/CD
  - configure a CI/CD pipeline for continuos deployment
- Production tips
  - In this section all the tips and tricks that fall into the category "I wish I knew that before deploy the app" e.g. SSL certificate. source map etc

Given there are a lot of CDN and CI/CD providers, this can get complicated but skills are transferable, so if the example covers netifly + travis CI should be enough, and can always be improved in the future

I'll be more than happy to contribute myself to this section of the cookbook 😄

**Comment by sdras** [comment]
This sounds like a really useful recipe. I'm really excited for this one. Thanks for contributing.

**Comment by matteo-hertel** [comment]
Awesome! I'll submit a PR once I'm done 😄

**Comment by phanan** [comment]
@matteo-hertel Any progress?

**Comment by matteo-hertel** [comment]
@phanan yes actually, I have a draft on a branch somewhere, but it was at the time vue cli was still in beta and never got around to update it, thanks for reminding me 👍
