### ISSUE TITLE
Dead link in detailed explanation of style guide->Element selectors with scoped

### ISSUE THREAD

**Issue by zumoshi** [vuejs/v2.vuejs.org#2563]
In this section:
https://vuejs.org/v2/style-guide/#Element-selectors-with-scoped-use-with-caution

The following link:
http://stevesouders.com/efws/css-selectors/csscreate.php?n=1000&sel=a%5Bhref%5D&body=background%3A+%23CFD&ne=1000

Captioned as `element-attribute selectors` returns 404.

![image](https://user-images.githubusercontent.com/4184939/80118830-2c226500-859e-11ea-9d3d-aa91c66bd3b8.png)

**Comment by Jinjiang** [comment]
Oops. Well... seems there are some mistakes in that website. I personally suggest to update the link to the relevant blog post: https://www.stevesouders.com/blog/2009/03/10/performance-impact-of-css-selectors/ temporarily instead. But not sure it's OK.

**Comment by Bamblehorse** [comment]
Looks like this is fixed with https://github.com/vuejs/docs/blob/4429b73a16dfa80b3a970e2bba0e17b4aefd3555/src/style-guide/rules-use-with-caution.md
