### ISSUE TITLE
debugging-in-vscode config not working for me

### ISSUE THREAD

**Issue by martixy** [vuejs/v2.vuejs.org#2617]
https://github.com/vuejs/vuejs.org/blob/master/src/v2/cookbook/debugging-in-vscode.md

The config here is not working for me.

The actual mapped files end up being `<projectDir>\src\js\webpack:\src\<pathToFile>`.  
(The first `src` there comes from the `webroot` setting.)

I am on a vue-cli project, compiling from the gui.

My env is:  
`vscode v1.45.1`  
`vue@2.6.11`
`@vue/cli@4.2.3`  
`node v13.8.0`  
`webpack@4.43.0`

The config that worked for me is:
```
{
    "webRoot": "${workspaceFolder}/",
    "sourceMapPathOverrides": {
        "webpack:///./*": "${webRoot}/*"
    }
}
```

I could have sworn the config from the docs worked a few weeks ago. But now I can replicate the problem(and above solution) across a number of projects.

I'm not sure if this is something isolated to my environment or a proper bug/bad docs...

**Comment by eloekset** [comment]
Are you sure the documentation about launch.json in VSCode is still valid?
```
   {
      "type": "chrome",
      "request": "launch",
      "name": "vuejs: chrome",
      "url": "http://localhost:8080",
      "webRoot": "${workspaceFolder}/src",
      "breakOnLoad": true,
      "sourceMapPathOverrides": {
        "webpack:///src/*": "${webRoot}/*"
      }
    },
```
![image](https://user-images.githubusercontent.com/791721/153064370-ae7eeb19-61bb-49f8-9f4b-a6bb66bf2c01.png)
![image](https://user-images.githubusercontent.com/791721/153064691-700af614-9a55-4609-a51a-63d10678cb69.png)
![image](https://user-images.githubusercontent.com/791721/153065334-1d6709d9-13a9-47ba-8dc6-56dd3cf2543f.png)
![image](https://user-images.githubusercontent.com/791721/153065395-22b5a493-6dff-4631-8115-faf396cfc7c2.png)
