### ISSUE TITLE
Link to v2.vuejs.org page in description of repository details

### ISSUE THREAD

**Issue by dpschen** [vuejs/v2.vuejs.org#2962]
## Current
The description of the repository details is linking to the documentation of vue.js 3.

## Expected
It should link to the archived v2 documentation instead [https://v2.vuejs.org](https://v2.vuejs.org)

<img width="360" alt="image" src="https://user-images.githubusercontent.com/6173598/184819276-63af6d05-3a2a-46c1-bf10-2311d07cc0b5.png">

**Comment by Jinjiang** [comment]
Nice catch! Fixed with thanks.
