### ISSUE TITLE
v-bind:style use quotes with kebab-case did not work

### ISSUE THREAD

**Issue by hua-qi** [vuejs/v2.vuejs.org#2963]
[document link](https://v2.vuejs.org/v2/guide/class-and-style.html#Binding-Inline-Styles)

![document image](https://user-images.githubusercontent.com/77103525/186127833-56e58fa6-c04b-488d-b2fe-78e110feef54.png)

Use quotes with kebab-case for the CSS property names that did not work.

![image](https://user-images.githubusercontent.com/77103525/186128601-6f22b963-d0e5-4b32-b298-0b43903448ad.png)

env:

windows 10

Chrome 104.0.5112.81

**Comment by Jinjiang** [comment]
> When using in-DOM templates (i.e., templates written directly in an HTML file), you should also avoid naming keys with uppercase characters, as browsers will coerce attribute names into lowercase:

https://v2.vuejs.org/v2/guide/syntax.html

**Comment by hua-qi** [comment]
The document is not rigorous enough.
Should it be changed?

**Comment by Jinjiang** [comment]
"font-size" need a string with a length unit. E.g. "font-size": "32px" works but "font-size": 32 won't.
