### ISSUE TITLE
French translation of v2 website is broken : 404 page

### ISSUE THREAD

**Issue by maxerbox** [vuejs/v2.vuejs.org#2967]
https://fr.vuejs.org/index.html

**Comment by yyx990803** [comment]
This seems to be caused by GitHub page's domain registration mechanism change. The site was deployed from a repo outside of the vuejs org, so its subdomain was invalidated when I verified vuejs.org root domain from the vuejs org.

We are looking to see who has access to the repo to fix this.

**Comment by maxerbox** [comment]
> This seems to be caused by GitHub page's domain registration mechanism change. The site was deployed from a repo outside of the vuejs org, so its subdomain was invalidated when I verified vuejs.org root domain from the vuejs org.
> 
> We are looking to see who has access to the repo to fix this.

Should be https://github.com/vuejs-fr/vuejs.org

**Comment by MachinisteWeb** [comment]
Hello @yyx990803 and @maxerbox

I'm one of people that have full access to the repo for the French translation of Vue.js version 2

What I can do to help solve this?

**Comment by MachinisteWeb** [comment]
So currently the website is available at: https://vuejs-fr.github.io/vuejs.org/ (but unfortunately CSS and JSS are called from a absolute path that not take in account the `/vuejs.org/` slug part.

To made it work from https://fr.vuejs.org, we have put a CNAME file at first place.

**Comment by yyx990803** [comment]
@MachinisteWeb we will need to verify fr.vuejs.org for github pages under the `vuejs-fr` organization. You can either give me admin access to the org or start the verification (org -> Settings -> Pages -> add a domain) and then send me the DNS challenge details via private messages.

**Comment by MachinisteWeb** [comment]
I will add you @yyx990803  as owner of org for safety in case of. You should be able to proceed in the first way you suggest right now.

Can be interesting to proceed in the second way you mention in the futur but I would not be in the position need to bother you each time we need a website update (the current workflow fork fine for us). So if it's really easy right now with Vercel/Netlify, we can try it right now. If not, probably should do it later after some investigation from our side to understand how it's work.

**Comment by maxerbox** [comment]
Fixed
